<playlist>
	<song url="./mod/000.delicate.mod" hasCredits="true" />
	<song url="./mod/001.marioland.mod" hasCredits="true" />
	<song url="./mod/002.CLASS11.MOD" hasCredits="true" />
	<song url="./mod/003.happy.mod" hasCredits="true" />
	<song url="./mod/004.madness.mod" hasCredits="true" />
	<song url="./mod/005.MARIO.MOD" hasCredits="true" />
	<song url="./mod/006.analyzer.mod" hasCredits="true" />
	<song url="./mod/007.hazel-arabian_night.mod" hasCredits="true" />
	<song url="./mod/accelerator.mod" hasCredits="true" />
	<song url="./mod/air_on_a_cz.mod" hasCredits="true" />
	<song url="./mod/ariadniphobia.mod" hasCredits="true" />
	<song url="./mod/autobahn-subculture.mod" hasCredits="true" />
	<song url="./mod/axel_f.mod" hasCredits="true" />
	<song url="./mod/blue3.mod" hasCredits="true" />
	<song url="./mod/boingbum.mod" hasCredits="true" />
	<song url="./mod/bytten_down.mod" hasCredits="true" />
	<song url="./mod/castlemorten.mod" hasCredits="true" />
	<song url="./mod/charlemange.mod" hasCredits="true" />
	<song url="./mod/CLASS12.MOD" hasCredits="true" />
	<song url="./mod/complex.mod" hasCredits="true" />
	<song url="./mod/eat_the_ballbearing.mod" hasCredits="true" />
	<song url="./mod/electrick.mod" hasCredits="true" />
	<song url="./mod/flight(sleepy_mix).mod" hasCredits="true" />
	<song url="./mod/flight.mod" hasCredits="true" />
	<song url="./mod/float.mod" hasCredits="true" />
	<song url="./mod/front242.mod" hasCredits="true" />
	<song url="./mod/Hazel - Coffee Jungle.mod" hasCredits="true" />
	<song url="./mod/hysterisis.mod" hasCredits="true" />
	<song url="./mod/introchaser.mod" hasCredits="true" />
	<song url="./mod/manic_trip_city.mod" hasCredits="true" />
	<song url="./mod/meta_thewilderness.mod" hasCredits="true" />
	<song url="./mod/mindbreak.mod" hasCredits="true" />
	<song url="./mod/nasty_buzzy_noise.mod" hasCredits="true" />
	<song url="./mod/non-biological_action.mod" hasCredits="true" />
	<song url="./mod/nostalgia.mod" hasCredits="true" />
	<song url="./mod/not_an_act_of_love.mod" hasCredits="true" />
	<song url="./mod/OWNAGE.MOD" hasCredits="true" />
	<song url="./mod/pulstar-subculture.mod" hasCredits="true" />
	<song url="./mod/RAINFORE.MOD" hasCredits="true" />
	<song url="./mod/relief.mod" hasCredits="true" />
	<song url="./mod/SAC14.MOD" hasCredits="true" />
	<song url="./mod/scroll_this.mod" hasCredits="true" />
	<song url="./mod/secret_garden.mod" hasCredits="true" />
	<song url="./mod/seduce.mod" hasCredits="true" />
	<song url="./mod/serendipity_city(trancefusion_mix).mod" hasCredits="true" />
	<song url="./mod/serendipity_city.mod" hasCredits="true" />
	<song url="./mod/shaft.mod" hasCredits="true" />
	<song url="./mod/skidrow.mod" hasCredits="true" />
	<song url="./mod/somebody.mod" hasCredits="true" />
	<song url="./mod/son_of_serendipity.mod" hasCredits="true" />
	<song url="./mod/spaedophilia.mod" hasCredits="true" />
	<song url="./mod/speedtrash.mod" hasCredits="true" />
	<song url="./mod/speedwork(remix).mod" hasCredits="true" />
	<song url="./mod/speedwork.mod" hasCredits="true" />
	<song url="./mod/sterilize(ohhhhhhh_james_mix).mod" hasCredits="true" />
	<song url="./mod/sterilize.mod" hasCredits="true" />
	<song url="./mod/stratospheric_city.mod" hasCredits="true" />
	<song url="./mod/subculture's_theme.mod" hasCredits="true" />
	<song url="./mod/subcultures_theme_2.mod" hasCredits="true" />
	<song url="./mod/sukcorperatdik.mod" hasCredits="true" />
	<song url="./mod/test.mod" hasCredits="true" />
	<song url="./mod/tetramagnetic.mod" hasCredits="true" />
	<song url="./mod/the_fly.mod" hasCredits="true" />
	<song url="./mod/this_is_not_a_rave_song.mod" hasCredits="true" />
	<song url="./mod/time_is_bunk.mod" hasCredits="true" />
	<song url="./mod/TLITS.MOD" hasCredits="true" />
	<song url="./mod/trier.mod" hasCredits="true" />
	<song url="./mod/ultra-vivid_dream.mod" hasCredits="true" />
	<song url="./mod/vagueodrome.mod" hasCredits="true" />
	<song url="./mod/var_4rom_earf.mod" hasCredits="true" />
	<song url="./mod/vworp.mod" hasCredits="true" />
</playlist>